services:
  anki:
    image: headless-anki:pypi-1.0.0
    volumes:
      - ./data:/data
    ports:
      - "5900:5900"
      - "8765:8765"  # AnkiConnect
      - "3141:3141"  # Anki MCP Server
    environment:
      - QT_QPA_PLATFORM=vnc
