services:
  anki:
    image: headless-anki:addons-1.0.0
    volumes:
      - ./data/prefs21.db:/data/prefs21.db
      # Mount custom addons like this:
      # - ./my-addon:/data/addons21/12345678
    ports:
      - "5900:5900"
